### ISSUE TITLE
NoClassDefFoundError: org/eclipse/tahu/message/SparkplugBPayloadDecoder

### ISSUE THREAD

**Issue by divakarlasrinivas** [RickBullotta/hivemq-sparkplugexpander-extension#1]
Hi, 

I am getting below mentioned error, could you help me out with this one please

```
2023-07-10 14:52:55,662 WARN  - Uncaught exception was thrown from extension with id "hivemq-sparkplugexpander-extension" on inbound PUBLISH interception. Extensions are responsible for their own exception handling.
java.lang.NoClassDefFoundError: org/eclipse/tahu/message/SparkplugBPayloadDecoder
	at com.industry40.common.sparkplug.SparkplugExpanderInterceptor.onInboundPublish(SparkplugExpanderInterceptor.java:112)
	at hmq.dQ.f$b.a(Source.java:297)
	at hmq.dQ.f$b.apply(Source.java:264)
	at hmq.dP.q$b.a(Source.java:363)
	at hmq.dP.q$b.c(Source.java:331)
	at hmq.dP.q$b.b(Source.java:280)
	at hmq.dP.q$b.run(Source.java:193)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: org.eclipse.tahu.message.SparkplugBPayloadDecoder
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at hmq.dE.a.loadClass(Source.java:148)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 12 common frames omitted
```

**Comment by TallRob46** [comment]
Were you able to resolve this one? I am running into the same issue.

**Comment by divakarlasrinivas** [comment]
Sorry I wasn’t able to resolve and gave up

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RickBullotta** [comment]
Are you building with the Maven project included in Github or did you create your own?  There are a few dependencies that the build should be including in the JAR file - this is one of them, along with protobuf

**Comment by TallRob46** [comment]
I used the maven project from the repo. 
Should the dependencies included in the lib directory be packaged into the extension or do they need to be installed on the machine running the broker? I first tried building the extension on a different machine than I was running the broker with, then tried building it on the machine with running the broker but had the same result.
